name: CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            VERSION=0.0.1
            sudo docker pull nathan9603/tech-lab:$VERSION
            sudo docker stop tech-lab || true
            sudo docker rm tech-lab || true
            sudo docker run -d --name tech-lab -p 8080:8080 nathan9603/tech-lab:$VERSION
