name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x ci-cd-test/gradlew


      - name: Build and Test with Gradle
        working-directory: ci-cd-test
        run: |
          ./gradlew build --no-daemon
          ./gradlew test --no-daemon

  docker:
    name: Build & Push Docker
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build-test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: nathan9603/tech-lab   # 👉 너의 Docker Hub 리포로 변경 가능
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          VERSION=0.0.1
          DATE_TAG=$(date +'%Y%m%d')
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build ./ci-cd-test \
            -f ./ci-cd-test/Dockerfile \
            -t $IMAGE_NAME:${DATE_TAG}-${SHORT_SHA}\
            -t $IMAGE_NAME:$VERSION

      - name: Push image
        run: |
          VERSION=0.0.1
          DATE_TAG=$(date +'%Y%m%d')
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker push $IMAGE_NAME:${DATE_TAG}-${SHORT_SHA}
          docker push $IMAGE_NAME:$VERSION
